# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47c305add1822f76a5ab81c6117d0f79"
name = "wishlist-inspire"
handle = "wishlist-inspire-384"
application_url = "https://sought-fire-brooklyn-stewart.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sought-fire-brooklyn-stewart.trycloudflare.com/auth/callback",
  "https://sought-fire-brooklyn-stewart.trycloudflare.com/auth/shopify/callback",
  "https://sought-fire-brooklyn-stewart.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
